import { CLI_SCHEMA_VERSION, type CliCapabilities, type CliCapability } from './types'

export const P0_COMMANDS: CliCapability[] = [
  {
    name: 'capabilities',
    description: '输出当前版本支持的 CLI 能力、依赖和 schema 入口。',
    stability: 'stable',
    schema: 'schema capabilities --json',
    requires: [],
    examples: ['md-viewer capabilities --json'],
  },
  {
    name: 'schema',
    description: '输出命令参数、结果、warning 和 action 的机器可读 schema。',
    stability: 'stable',
    schema: 'schema schema --json',
    requires: [],
    examples: ['md-viewer schema --json', 'md-viewer schema export --json'],
  },
  {
    name: 'help',
    description: '输出人类帮助或 AI 可解析帮助。',
    stability: 'stable',
    schema: 'schema help --json',
    requires: [],
    examples: ['md-viewer help', 'md-viewer help export --json'],
  },
  {
    name: 'open',
    description: '打开 Markdown 文件或目录并聚焦 GUI。',
    stability: 'stable',
    schema: 'schema open --json',
    requires: ['electron-gui'],
    examples: ['md-viewer open README.md', 'md-viewer open /path/to/docs'],
  },
  {
    name: 'export',
    description: '后台导出 HTML、PDF 或 DOCX。',
    stability: 'stable',
    schema: 'schema export --json',
    requires: ['headless-renderer'],
    examples: [
      'md-viewer export README.md --format pdf --out README.pdf',
      'md-viewer export README.md --format docx --out README.docx',
    ],
  },
  {
    name: 'preflight',
    description: '导出前检查单个文档和目标格式风险。',
    stability: 'stable',
    schema: 'schema preflight --json',
    requires: [],
    examples: ['md-viewer preflight README.md --format docx --json'],
  },
  {
    name: 'doctor',
    description: '检查当前机器、renderer artifact、DOCX 服务和可选依赖。',
    stability: 'stable',
    schema: 'schema doctor --json',
    requires: [],
    examples: ['md-viewer doctor --json'],
  },
  {
    name: 'screenshot',
    description: '生成整页、正文区域、选择器或单图表截图。',
    stability: 'stable',
    schema: 'schema screenshot --json',
    requires: ['headless-renderer'],
    examples: ['md-viewer screenshot README.md --selector ".markdown-body" --out README.png'],
  },
  {
    name: 'charts',
    description: '列出或导出文档中的图表。',
    stability: 'stable',
    schema: 'schema charts --json',
    requires: ['headless-renderer'],
    examples: ['md-viewer charts list README.md --json', 'md-viewer charts export README.md --out-dir README-charts'],
  },
  {
    name: 'batch',
    description: '批量执行真实文档回归并生成报告。',
    stability: 'stable',
    schema: 'schema batch --json',
    requires: ['headless-renderer'],
    examples: ['md-viewer batch e2e/local-real-docs.json --out test-results/release-report.json'],
  },
  {
    name: 'install-cli',
    description: '在 macOS、Windows 或 Linux 上安装 md-viewer 命令行入口。',
    stability: 'stable',
    schema: 'schema install-cli --json',
    requires: ['desktop-app'],
    examples: ['"/Applications/MD Viewer.app/Contents/MacOS/MD Viewer" install-cli --json'],
  },
  {
    name: 'uninstall-cli',
    description: '移除 MD Viewer 生成的 md-viewer 命令行入口。',
    stability: 'stable',
    schema: 'schema uninstall-cli --json',
    requires: ['desktop-app'],
    examples: ['md-viewer uninstall-cli --json'],
  },
]

export const P1_COMMANDS: CliCapability[] = [
  {
    name: 'inspect',
    description: '分析 Markdown 结构、链接、图片和图表风险。',
    stability: 'experimental',
    schema: 'schema inspect --json',
    requires: [],
    examples: ['md-viewer inspect README.md --json'],
  },
  {
    name: 'render',
    description: '输出中间渲染 HTML 或 JSON。',
    stability: 'experimental',
    schema: 'schema render --json',
    requires: ['headless-renderer'],
    examples: ['md-viewer render README.md --out render.html --json'],
  },
  {
    name: 'links',
    description: '检查 Markdown 本地链接、锚点和可选外链。',
    stability: 'experimental',
    schema: 'schema links --json',
    requires: [],
    examples: ['md-viewer links README.md --json'],
  },
]

export function getRegisteredCapabilities(): CliCapabilities {
  return {
    schemaVersion: CLI_SCHEMA_VERSION,
    commands: [
      ...P0_COMMANDS,
      ...P1_COMMANDS,
    ],
    formats: ['html', 'pdf', 'docx', 'png', 'zip'],
    chartTypes: [
      'mermaid',
      'echarts',
      'markmap',
      'graphviz',
      'plantuml',
      'drawio',
      'infographic',
      'katex',
      'excalidraw',
      'vega-lite',
      'd2',
      'bpmn',
      'wavedrom',
      'c4plantuml',
      'structurizr',
      'plotly',
      'dbml',
      'antv-g6',
      'kroki',
    ],
    networkPolicy: 'disabled-by-default',
  }
}
