import { constants } from 'fs'
import * as fs from 'fs/promises'
import * as os from 'os'
import * as path from 'path'

const SHIM_NAME = 'md-viewer'
const SHIM_MARKER = '# Generated by MD Viewer CLI installer'

export interface CliShimFs {
  mkdir: (dirPath: string, options?: { recursive?: boolean }) => Promise<unknown>
  writeFile: (filePath: string, content: string, encoding: BufferEncoding) => Promise<unknown>
  chmod: (filePath: string, mode: number) => Promise<unknown>
  rm: (filePath: string, options?: { force?: boolean }) => Promise<unknown>
  readFile: (filePath: string, encoding: BufferEncoding) => Promise<string>
  access: (filePath: string, mode?: number) => Promise<unknown>
}

export interface CliShimInstallOptions {
  appExecutablePath?: string
  appImagePath?: string
  envPath?: string
  homeDir?: string
  localAppDataDir?: string
  platform?: NodeJS.Platform
  fs?: CliShimFs
}

export interface CliShimUninstallOptions {
  platform?: NodeJS.Platform
  homeDir?: string
  localAppDataDir?: string
  fs?: CliShimFs
}

export interface CliShimResult {
  ok: boolean
  path?: string
  pathInShell?: boolean
  nextStep?: string
  code?: string
  message?: string
}

export interface CliShimStatus {
  supported: boolean
  installed: boolean
  platform: NodeJS.Platform
  path?: string
  pathInShell?: boolean
  ownedByMdViewer?: boolean
  code?: string
  message?: string
}

const nodeFs: CliShimFs = {
  mkdir: fs.mkdir,
  writeFile: fs.writeFile,
  chmod: fs.chmod,
  rm: fs.rm,
  readFile: fs.readFile,
  access: fs.access,
}

export async function installCliShim(options: CliShimInstallOptions = {}): Promise<CliShimResult> {
  const platform = options.platform ?? process.platform
  if (!isSupportedPlatform(platform)) {
    return {
      ok: false,
      code: 'CLI_SHIM_UNSUPPORTED_PLATFORM',
      message: '当前自动安装命令行工具仅支持 macOS、Windows 和 Linux。',
    }
  }

  const fsApi = options.fs ?? nodeFs
  const homeDir = options.homeDir ?? os.homedir()
  const appExecutablePath = resolveAppExecutablePath(platform, options)
  const targetDir = await chooseShimDir(fsApi, platform, homeDir, options.localAppDataDir)
  const pathApi = getPathApi(platform)
  const targetPath = pathApi.join(targetDir, getShimFileName(platform))
  const content = createShimContent(platform, appExecutablePath)
  const existingContent = await readOptionalFile(fsApi, targetPath)

  if (existingContent !== null && !isOwnedByMdViewer(existingContent)) {
    return {
      ok: false,
      path: targetPath,
      code: 'CLI_SHIM_NOT_OWNED',
      message: `已存在 ${targetPath}，但不是 MD Viewer 生成的命令，已跳过覆盖。`,
    }
  }

  await fsApi.mkdir(targetDir, { recursive: true })
  await fsApi.writeFile(targetPath, content, 'utf8')
  if (platform !== 'win32') {
    await fsApi.chmod(targetPath, 0o755)
  }

  const envPath = options.envPath ?? process.env.PATH ?? ''
  const pathInShell = isDirInPath(platform, targetDir, envPath)
  return {
    ok: true,
    path: targetPath,
    pathInShell,
    nextStep: buildInstallNextStep(platform, targetDir, pathInShell),
  }
}

export async function uninstallCliShim(options: CliShimUninstallOptions = {}): Promise<CliShimResult> {
  const platform = options.platform ?? process.platform
  if (!isSupportedPlatform(platform)) {
    return {
      ok: false,
      code: 'CLI_SHIM_UNSUPPORTED_PLATFORM',
      message: '当前自动卸载命令行工具仅支持 macOS、Windows 和 Linux。',
    }
  }

  const fsApi = options.fs ?? nodeFs
  const homeDir = options.homeDir ?? os.homedir()
  const candidates = getShimCandidatePaths(platform, homeDir, options.localAppDataDir)

  for (const candidate of candidates) {
    const content = await readOptionalFile(fsApi, candidate)
    if (content === null) continue

    if (!isOwnedByMdViewer(content)) {
      return {
        ok: false,
        path: candidate,
        code: 'CLI_SHIM_NOT_OWNED',
        message: `已存在 ${candidate}，但不是 MD Viewer 生成的命令，已跳过删除。`,
      }
    }

    await fsApi.rm(candidate, { force: true })
    return {
      ok: true,
      path: candidate,
      nextStep: '重新打开终端后，md-viewer 命令将不再可用。',
    }
  }

  return {
    ok: true,
    nextStep: '未找到 MD Viewer 生成的 md-viewer 命令。',
  }
}

export async function getCliShimStatus(options: CliShimInstallOptions = {}): Promise<CliShimStatus> {
  const platform = options.platform ?? process.platform
  if (!isSupportedPlatform(platform)) {
    return {
      supported: false,
      installed: false,
      platform,
      code: 'CLI_SHIM_UNSUPPORTED_PLATFORM',
      message: '当前自动安装命令行工具仅支持 macOS、Windows 和 Linux。',
    }
  }

  const fsApi = options.fs ?? nodeFs
  const homeDir = options.homeDir ?? os.homedir()
  const envPath = options.envPath ?? process.env.PATH ?? ''
  const candidates = getShimCandidatePaths(platform, homeDir, options.localAppDataDir)

  for (const candidate of candidates) {
    const content = await readOptionalFile(fsApi, candidate)
    if (content === null) continue

    const ownedByMdViewer = isOwnedByMdViewer(content)
    return {
      supported: true,
      installed: ownedByMdViewer,
      platform,
      path: candidate,
      pathInShell: isDirInPath(platform, getPathApi(platform).dirname(candidate), envPath),
      ownedByMdViewer,
      code: ownedByMdViewer ? undefined : 'CLI_SHIM_NOT_OWNED',
      message: ownedByMdViewer
        ? undefined
        : `已存在 ${candidate}，但不是 MD Viewer 生成的命令。`,
    }
  }

  return {
    supported: true,
    installed: false,
    platform,
  }
}

async function chooseShimDir(
  fsApi: CliShimFs,
  platform: NodeJS.Platform,
  homeDir: string,
  localAppDataDir?: string,
): Promise<string> {
  if (platform === 'win32') {
    return path.win32.join(localAppDataDir ?? process.env.LOCALAPPDATA ?? path.win32.join(homeDir, 'AppData', 'Local'), 'MD Viewer', 'bin')
  }

  if (platform === 'linux') {
    return path.posix.join(homeDir, '.local/bin')
  }

  try {
    await fsApi.access('/usr/local/bin', constants.W_OK)
    return '/usr/local/bin'
  } catch {
    return path.posix.join(homeDir, '.local/bin')
  }
}

function getShimCandidatePaths(platform: NodeJS.Platform, homeDir: string, localAppDataDir?: string): string[] {
  if (platform === 'win32') {
    const baseDir = localAppDataDir ?? process.env.LOCALAPPDATA ?? path.win32.join(homeDir, 'AppData', 'Local')
    return [path.win32.join(baseDir, 'MD Viewer', 'bin', getShimFileName(platform))]
  }

  return [
    path.posix.join('/usr/local/bin', SHIM_NAME),
    path.posix.join(homeDir, '.local/bin', SHIM_NAME),
  ]
}

function createShimContent(platform: NodeJS.Platform, appExecutablePath: string): string {
  if (platform === 'win32') {
    return [
      '@echo off',
      `REM ${SHIM_MARKER}`,
      `"${appExecutablePath}" %*`,
      '',
    ].join('\r\n')
  }

  return [
    '#!/bin/sh',
    SHIM_MARKER,
    `exec "${escapeDoubleQuotedShell(appExecutablePath)}" "$@"`,
    '',
  ].join('\n')
}

function resolveAppExecutablePath(platform: NodeJS.Platform, options: CliShimInstallOptions): string {
  if (options.appExecutablePath) {
    return options.appExecutablePath
  }

  if (platform === 'linux') {
    return options.appImagePath ?? process.env.APPIMAGE ?? process.execPath
  }

  return process.execPath
}

function getShimFileName(platform: NodeJS.Platform): string {
  return platform === 'win32' ? `${SHIM_NAME}.cmd` : SHIM_NAME
}

function getPathApi(platform: NodeJS.Platform): typeof path.win32 | typeof path.posix {
  return platform === 'win32' ? path.win32 : path.posix
}

function isDirInPath(platform: NodeJS.Platform, dirPath: string, envPath: string): boolean {
  const pathApi = getPathApi(platform)
  const delimiter = platform === 'win32' ? ';' : ':'
  return envPath
    .split(delimiter)
    .filter(Boolean)
    .some(entry => {
      const resolvedEntry = pathApi.resolve(entry)
      const resolvedDir = pathApi.resolve(dirPath)
      return platform === 'win32'
        ? resolvedEntry.toLowerCase() === resolvedDir.toLowerCase()
        : resolvedEntry === resolvedDir
    })
}

function buildInstallNextStep(platform: NodeJS.Platform, targetDir: string, pathInShell: boolean): string {
  if (pathInShell) {
    return `重新打开终端后可直接运行：${SHIM_NAME} capabilities --json`
  }

  if (platform === 'win32') {
    return `请把命令目录加入用户 Path：${targetDir}，然后重新打开 PowerShell 或 CMD。`
  }

  if (platform === 'linux') {
    return `请把命令目录加入 PATH，例如在 ~/.bashrc 或 ~/.zshrc 中增加：export PATH="$HOME/.local/bin:$PATH"`
  }

  return `请把命令目录加入 PATH，例如在 ~/.zshrc 中增加：export PATH="$HOME/.local/bin:$PATH"`
}

function isSupportedPlatform(platform: NodeJS.Platform): boolean {
  return platform === 'darwin' || platform === 'win32' || platform === 'linux'
}

function isOwnedByMdViewer(content: string): boolean {
  return content.includes(SHIM_MARKER) || content.includes(SHIM_MARKER.replace(/^# /, ''))
}

function escapeDoubleQuotedShell(value: string): string {
  return value.replace(/(["\\$`])/g, '\\$1')
}

async function readOptionalFile(fsApi: CliShimFs, filePath: string): Promise<string | null> {
  try {
    return await fsApi.readFile(filePath, 'utf8')
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code === 'ENOENT') {
      return null
    }
    throw error
  }
}
