import { describe, expect, it, vi } from 'vitest'
import {
  getCliShimStatus,
  installCliShim,
  uninstallCliShim,
  type CliShimFs,
} from '../cliShimInstaller'

function createMemoryFs(options: {
  writableDirs?: string[]
  existingFiles?: Record<string, string>
} = {}) {
  const files = new Map<string, string>(Object.entries(options.existingFiles ?? {}))
  const writableDirs = new Set(options.writableDirs ?? [])
  const mkdir = vi.fn(async () => undefined)
  const writeFile = vi.fn(async (filePath: string, content: string) => {
    files.set(filePath, content)
  })
  const chmod = vi.fn(async () => undefined)
  const rm = vi.fn(async (filePath: string) => {
    files.delete(filePath)
  })
  const readFile = vi.fn(async (filePath: string) => {
    const content = files.get(filePath)
    if (content === undefined) {
      const error = new Error('not found') as NodeJS.ErrnoException
      error.code = 'ENOENT'
      throw error
    }
    return content
  })
  const access = vi.fn(async (dir: string) => {
    if (!writableDirs.has(dir)) {
      const error = new Error('not writable') as NodeJS.ErrnoException
      error.code = 'EACCES'
      throw error
    }
  })

  const fs: CliShimFs = { mkdir, writeFile, chmod, rm, readFile, access }
  return { fs, files, mkdir, writeFile, chmod, rm, readFile, access }
}

describe('cliShimInstaller', () => {
  it('installs md-viewer into /usr/local/bin when it is writable', async () => {
    const memory = createMemoryFs({ writableDirs: ['/usr/local/bin'] })

    const result = await installCliShim({
      appExecutablePath: '/Applications/MD Viewer.app/Contents/MacOS/MD Viewer',
      envPath: '/usr/local/bin:/usr/bin',
      homeDir: '/Users/tester',
      platform: 'darwin',
      fs: memory.fs,
    })

    expect(result.ok).toBe(true)
    expect(result.path).toBe('/usr/local/bin/md-viewer')
    expect(result.pathInShell).toBe(true)
    expect(memory.writeFile).toHaveBeenCalledWith(
      '/usr/local/bin/md-viewer',
      expect.stringContaining('exec "/Applications/MD Viewer.app/Contents/MacOS/MD Viewer" "$@"'),
      'utf8',
    )
    expect(memory.chmod).toHaveBeenCalledWith('/usr/local/bin/md-viewer', 0o755)
  })

  it('falls back to ~/.local/bin and reports PATH guidance when /usr/local/bin is not writable', async () => {
    const memory = createMemoryFs()

    const result = await installCliShim({
      appExecutablePath: '/Applications/MD Viewer.app/Contents/MacOS/MD Viewer',
      envPath: '/usr/local/bin:/usr/bin',
      homeDir: '/Users/tester',
      platform: 'darwin',
      fs: memory.fs,
    })

    expect(result.ok).toBe(true)
    expect(result.path).toBe('/Users/tester/.local/bin/md-viewer')
    expect(result.pathInShell).toBe(false)
    expect(result.nextStep).toContain('export PATH="$HOME/.local/bin:$PATH"')
  })

  it('does not overwrite an existing md-viewer file that was not generated by MD Viewer', async () => {
    const memory = createMemoryFs({
      writableDirs: ['/usr/local/bin'],
      existingFiles: {
        '/usr/local/bin/md-viewer': '#!/bin/sh\necho external\n',
      },
    })

    const result = await installCliShim({
      appExecutablePath: '/Applications/MD Viewer.app/Contents/MacOS/MD Viewer',
      envPath: '/usr/local/bin:/usr/bin',
      homeDir: '/Users/tester',
      platform: 'darwin',
      fs: memory.fs,
    })

    expect(result.ok).toBe(false)
    expect(result.code).toBe('CLI_SHIM_NOT_OWNED')
    expect(memory.writeFile).not.toHaveBeenCalled()
    expect(memory.files.get('/usr/local/bin/md-viewer')).toBe('#!/bin/sh\necho external\n')
  })

  it('does not uninstall a md-viewer file that was not generated by MD Viewer', async () => {
    const memory = createMemoryFs({
      existingFiles: {
        '/Users/tester/.local/bin/md-viewer': '#!/bin/sh\necho external\n',
      },
    })

    const result = await uninstallCliShim({
      homeDir: '/Users/tester',
      platform: 'darwin',
      fs: memory.fs,
    })

    expect(result.ok).toBe(false)
    expect(result.code).toBe('CLI_SHIM_NOT_OWNED')
    expect(memory.rm).not.toHaveBeenCalled()
  })

  it('reports installed status only for a MD Viewer generated shim', async () => {
    const memory = createMemoryFs({
      existingFiles: {
        '/Users/tester/.local/bin/md-viewer': '#!/bin/sh\n# Generated by MD Viewer CLI installer\nexec "/Applications/MD Viewer.app/Contents/MacOS/MD Viewer" "$@"\n',
      },
    })

    const result = await getCliShimStatus({
      homeDir: '/Users/tester',
      envPath: '/Users/tester/.local/bin:/usr/bin',
      platform: 'darwin',
      fs: memory.fs,
    })

    expect(result.installed).toBe(true)
    expect(result.path).toBe('/Users/tester/.local/bin/md-viewer')
    expect(result.ownedByMdViewer).toBe(true)
    expect(result.pathInShell).toBe(true)
  })

  it('reports conflict status for an existing non-MD Viewer shim', async () => {
    const memory = createMemoryFs({
      existingFiles: {
        '/usr/local/bin/md-viewer': '#!/bin/sh\necho external\n',
      },
    })

    const result = await getCliShimStatus({
      homeDir: '/Users/tester',
      envPath: '/usr/local/bin:/usr/bin',
      platform: 'darwin',
      fs: memory.fs,
    })

    expect(result.installed).toBe(false)
    expect(result.path).toBe('/usr/local/bin/md-viewer')
    expect(result.ownedByMdViewer).toBe(false)
    expect(result.code).toBe('CLI_SHIM_NOT_OWNED')
  })

  it('installs a Linux shell shim into ~/.local/bin', async () => {
    const memory = createMemoryFs()

    const result = await installCliShim({
      appExecutablePath: '/opt/MD Viewer/md-viewer',
      envPath: '/usr/bin',
      homeDir: '/home/tester',
      platform: 'linux',
      fs: memory.fs,
    })

    expect(result.ok).toBe(true)
    expect(result.path).toBe('/home/tester/.local/bin/md-viewer')
    expect(result.pathInShell).toBe(false)
    expect(memory.writeFile).toHaveBeenCalledWith(
      '/home/tester/.local/bin/md-viewer',
      expect.stringContaining('exec "/opt/MD Viewer/md-viewer" "$@"'),
      'utf8',
    )
    expect(memory.chmod).toHaveBeenCalledWith('/home/tester/.local/bin/md-viewer', 0o755)
    expect(result.nextStep).toContain('~/.bashrc')
  })

  it('uses the original AppImage path for Linux shim when available', async () => {
    const memory = createMemoryFs()

    const result = await installCliShim({
      appImagePath: '/home/tester/Downloads/MD-Viewer.AppImage',
      envPath: '/home/tester/.local/bin:/usr/bin',
      homeDir: '/home/tester',
      platform: 'linux',
      fs: memory.fs,
    })

    expect(result.ok).toBe(true)
    expect(memory.writeFile).toHaveBeenCalledWith(
      '/home/tester/.local/bin/md-viewer',
      expect.stringContaining('exec "/home/tester/Downloads/MD-Viewer.AppImage" "$@"'),
      'utf8',
    )
  })

  it('installs a Windows cmd shim into LocalAppData bin directory', async () => {
    const memory = createMemoryFs()

    const result = await installCliShim({
      appExecutablePath: 'C:\\Program Files\\MD Viewer\\MD Viewer.exe',
      envPath: 'C:\\Windows\\System32',
      homeDir: 'C:\\Users\\tester',
      localAppDataDir: 'C:\\Users\\tester\\AppData\\Local',
      platform: 'win32',
      fs: memory.fs,
    })

    expect(result.ok).toBe(true)
    expect(result.path).toBe('C:\\Users\\tester\\AppData\\Local\\MD Viewer\\bin\\md-viewer.cmd')
    expect(result.pathInShell).toBe(false)
    expect(memory.writeFile).toHaveBeenCalledWith(
      'C:\\Users\\tester\\AppData\\Local\\MD Viewer\\bin\\md-viewer.cmd',
      expect.stringContaining('"C:\\Program Files\\MD Viewer\\MD Viewer.exe" %*'),
      'utf8',
    )
    expect(memory.chmod).not.toHaveBeenCalled()
    expect(result.nextStep).toContain('Path')
  })

  it('reports installed status for a Windows generated cmd shim', async () => {
    const memory = createMemoryFs({
      existingFiles: {
        'C:\\Users\\tester\\AppData\\Local\\MD Viewer\\bin\\md-viewer.cmd':
          '@echo off\r\nREM Generated by MD Viewer CLI installer\r\n"C:\\Program Files\\MD Viewer\\MD Viewer.exe" %*\r\n',
      },
    })

    const result = await getCliShimStatus({
      homeDir: 'C:\\Users\\tester',
      localAppDataDir: 'C:\\Users\\tester\\AppData\\Local',
      envPath: 'C:\\Users\\tester\\AppData\\Local\\MD Viewer\\bin;C:\\Windows\\System32',
      platform: 'win32',
      fs: memory.fs,
    })

    expect(result.supported).toBe(true)
    expect(result.installed).toBe(true)
    expect(result.path).toBe('C:\\Users\\tester\\AppData\\Local\\MD Viewer\\bin\\md-viewer.cmd')
    expect(result.pathInShell).toBe(true)
  })
})
